### ISSUE TITLE
Undefined bug in @tsed/schema

### ISSUE THREAD

**Issue by shivanshtalwar0** [TypedProject/ts-express-decorators#3138]
### Describe the bug

when i ran the project after updating the dependencies from 8.7.1 to 8.14.1 i got 
I traced this bug inside
```js
    /**
     * Assign the types of the generics that must be used for the property
     * @param generics
     */
    genericOf(...generics) {
        const mapped = mapGenerics(this.#itemSchema || mapToJsonSchema(this.getTarget()), generics);
        this.vendorKey(VendorKeys.GENERIC_OF, mapped);
        return this;
    }
```
and error that i got was
file:///Users/utopia/myprojects/backend-api/auth-service/node_modules/@tsed/schema/lib/esm/domain/JsonSchema.js:48
    const genericLabels = jsonSchema.getGenericLabels();
                                     ^

TypeError: jsonSchema.getGenericLabels is not a function
    at mapGenerics (file:///Users/utopia/myprojects/backend-api/auth-service/node_modules/@tsed/schema/lib/esm/domain/JsonSchema.js:48:38)
    at JsonSchema.genericOf (file:///Users/utopia/myprojects/backend-api/auth-service/node_modules/@tsed/schema/lib/esm/domain/JsonSchema.js:270:24)
    at file:///Users/utopia/myprojects/backend-api/auth-service/node_modules/@tsed/schema/lib/esm/decorators/operations/returns.js:116:28
    at file:///Users/utopia/myprojects/backend-api/auth-service/node_modules/@tsed/schema/lib/esm/domain/DecoratorContext.js:77:13
    at Array.forEach (<anonymous>)
    at ReturnDecoratorContext.runActions (file:///Users/utopia/myprojects/backend-api/auth-service/node_modules/@tsed/schema/lib/esm/domain/DecoratorContext.js:76:22)
    at ReturnDecoratorContext.map (file:///Users/utopia/myprojects/backend-api/auth-service/node_modules/@tsed/schema/lib/esm/decorators/operations/returns.js:223:21)
    at ReturnDecoratorContext.onInit (file:///Users/utopia/myprojects/backend-api/auth-service/node_modules/@tsed/schema/lib/esm/decorators/operations/returns.js:188:26)
    at ReturnDecoratorContext.bind (file:///Users/utopia/myprojects/backend-api/auth-service/node_modules/@tsed/schema/lib/esm/domain/DecoratorContext.js:64:14)
    at decorator (file:///Users/utopia/myprojects/backend-api/auth-service/node_modules/@tsed/schema/lib/esm/domain/DecoratorContext.js:20:45)

Node.js v20.19.0

### To Reproduce

just run the project with prisma

### Expected behavior

It should run as normal

### Code snippets

```TypeScript

```

### OS

macos m1

### Node version

20.19.0

### Library version

8.14.1

**Comment by Romakita** [comment]
Hello @shivanshtalwar0 
Please give me the concerned model that fail. Without a reproducible code example I'll close this issue ;). But based on your stack, it seems related to Returns() decorator, you have a some wrong with the configured metadata that isn't covered by the integration test.

See you

**Comment by shivanshtalwar0** [comment]
Okay i will look into returns and get back to you

**Comment by shivanshtalwar0** [comment]
Hey @Romakita  i have an update, turns out the issue happened due to two things in my own library built on top of tsed, but yeah as you said it was in returns decorator used inside the library, i wish we could have generic code out of the box to give out basic crud operation on a Prisma model and repository so that lot of boiler plate code while making crud can be avoided right now i do this with my own library but i believe many users of tsed can benefit from it i am open to discussion on potential integration if you feel right.
Once again thank you for the wonderful support 
Regards.
Shivansh Talwar

**Comment by Romakita** [comment]
Sure @shivanshtalwar0 it could be interesting. Also use  decorators in this case isn’t probably the right solution if you haven’t the model during the decorator usage.
 
I work actively to improve schema api to separate code from decorators. 
I think if you share your implementation I’ll be able to understand how you done that and how I can improve the schema API ;)

**Comment by shivanshtalwar0** [comment]
@Romakita Hi mate,
https://github.com/januscaler/tsed-helper i developed this package to help me implement generic crud operations and i use this code as pair of controler.ts and service.ts example shown below.
```js
//Controler.ts
import { BodyParams, Controller, PathParams } from '@tsed/common';
import { inject } from '@tsed/di';
import { Groups } from '@tsed/schema';
import { RegionCountryModel } from '@tsed/prisma';
import { createItem, deleteItem, getItem, getItems, SearchParams, updateItem } from '@januscaler/tsed-helper';
import { RoleBasedAuthorization } from '../../../decorators/index.js';
import { RegionCountryService } from './service.js';

@RoleBasedAuthorization()
@Controller('/countries')
export class RegionCountryController {
	service: RegionCountryService = inject(RegionCountryService);

	@createItem({ model: RegionCountryModel })
	async createItem(@BodyParams() @Groups('create') permission: RegionCountryModel): Promise<any> {
		return this.service.create(permission);
	}

	@deleteItem({ model: RegionCountryModel })
	async deleteItem(@PathParams('id') id: number): Promise<any> {
		return this.service.deleteItem(id);
	}

	@getItem({ model: RegionCountryModel })
	async getOne(@PathParams('id') id: number): Promise<any> {
		return this.service.getOne(id);
	}

	@updateItem({ model: RegionCountryModel })
	async update(@PathParams('id') id: number, @BodyParams() @Groups('update') role: RegionCountryModel): Promise<any> {
		return this.service.update(id, role);
	}

	@getItems({ model: RegionCountryModel })
	getAll(@BodyParams() searchParams: SearchParams) {
		return this.service.getAll({
			...searchParams
		});
	}
}
```
```js
//Service.ts
import _ from 'lodash';
import { inject, Service } from '@tsed/di';
import { PrismaService, RegionCountriesRepository } from '@tsed/prisma';
import { BaseService } from '@januscaler/tsed-helper';

@Service()
export class RegionCountryService extends BaseService<RegionCountriesRepository> {
	constructor() {
		super(inject(RegionCountriesRepository), inject(PrismaService));
	}
}
```
I know it seems still verbose but avoid rewriting same functionality for different prisma models 
Not sure if this can help you but worth sharing with you and community

**Comment by Romakita** [comment]
Perfect I'll take a time to integrate your code example in my integration test and see I can publish a schema utility to resolve your issue :)

**Comment by Romakita** [comment]
I haven't found @januscaler/tsed-helper on npm ^^, it's nomal ?

**Comment by shivanshtalwar0** [comment]
@Romakita that's normal coz it is private github package you can install locally using npm run build && npm run pack

**Comment by shivanshtalwar0** [comment]
@Romakita btw my issue was resolved i just shared so that maybe my efforts can help the tsed community

**Comment by Romakita** [comment]
Yes your code example is very valuable and could be a good learning to improve the tsed ecosystem ;)

I have in mind a version that can use the service and the model to generate the doc correctly.

**Comment by shivanshtalwar0** [comment]
Looking forward to it 😄

**Comment by shivanshtalwar0** [comment]
@Romakita  i have updated main branch to v2/prod-v2 branch i hope you saw prod-v2 and not prod as it has old obsolete code
