### PR TITLE
fix(prisma): resolve several issues with prisma generate for ESM

### PR DESCRIPTION
**Pull request by vangie**
1. Correct the generated 'lib/esm/index.js' file's path.
2. Workaround for 'ReferenceError: Cannot access 'xxx' before initialization' caused by esm circular ref.

```
../tsed/packages/orm/prisma/lib/esm/.schema/models/MessageModel.js:129
    __metadata("design:type", ConversationModel)
                              ^

ReferenceError: Cannot access 'ConversationModel' before initialization
    at ../tsed/packages/orm/prisma/lib/esm/.schema/models/MessageModel.js:129:31
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.11.1
```

## Information

| Type                  | Breaking change |
| --------------------- | --------------- |
| Feature/Fix/Doc/Chore | Yes/No          |

---

## Todos

- [ ] Tests
- [ ] Coverage
- [ ] Example
- [ ] Documentation

### CODE REVIEW

File: packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts [hunk 1]
```diff
@@ -15,7 +16,9 @@ function createDecorator(name: string, args: string[]): DecoratorStructure {
 
 export function transformFieldToDecorators(field: DmmfField, ctx: TransformContext): DecoratorStructure[] {
   const hasCircularRef = isCircularRef(field.model.name, field.type, ctx);
-
+  if (isEsm() && hasCircularRef) {
```
Comment (Romakita) [inline packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts]: but in this case, a lot of decorators won't be generated...

File: packages/orm/prisma/src/generator.ts [hunk 2]
```diff
@@ -4,8 +4,8 @@ import {join} from "path";
 import {generate} from "./cli/prismaGenerator";
 
 const rootDir = __dirname; // automatically replaced by tsed tools on build
-export const defaultOutput = join(rootDir, "..", ".schema");
-export const packageDir = join(rootDir, "..", "..", "..");
+export const defaultOutput = join(rootDir, ".schema");
```
Comment (Romakita) [inline packages/orm/prisma/src/generator.ts]: this path shouldn't change

File: packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts (hunk 1 above)
Comment (vangie) [reply packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts]: I don't know howto fix following issue in esm , any sugguest？

```
../tsed/packages/orm/prisma/lib/esm/.schema/models/MessageModel.js:129
    __metadata("design:type", ConversationModel)
                              ^

ReferenceError: Cannot access 'ConversationModel' before initialization
    at ../tsed/packages/orm/prisma/lib/esm/.schema/models/MessageModel.js:129:31
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.11.1
```

File: packages/orm/prisma/src/generator.ts (hunk 2 above)
Comment (vangie) [reply packages/orm/prisma/src/generator.ts]: if not change defaultOutput，files would generate to folder './../tsed/packages/orm/prisma/lib/.schema' and meet some error. After I remove a '..', files generated to folder './../tsed/packages/orm/prisma/lib/esm/.schema', the error is gone.  So by design which folder is right？

Comment (Romakita) [reply packages/orm/prisma/src/generator.ts]: it should be  './../tsed/packages/orm/prisma/lib/.schema'

Comment (Romakita) [reply packages/orm/prisma/src/generator.ts]: I publish just before your PR a small fixes on Prisma for your issue. So maybe isn't longer an issue ;)

File: packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts (hunk 1 above)
Comment (Romakita) [reply packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts]: we should wrap the ConversationModel into an arrow function instead adding it directly in the concerned decorator

Comment (Romakita) [reply packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts]: Eg: Property(() => ConversationModel)

File: packages/orm/prisma/src/generator.ts (hunk 2 above)
Comment (vangie) [reply packages/orm/prisma/src/generator.ts]: After rebasing the 'production' branch and regenerate,  I encountered the following error when starting my project:

```
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/duwan/Workspaces/babelcloud/tsed/packages/orm/prisma/lib/esm/.schema/index.js' imported from /Users/duwan/Workspaces/babelcloud/tsed/packages/orm/prisma/lib/esm/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at nextResolve (node:internal/modules/esm/hooks:865:28)
    at resolve (file:///Users/duwan/Workspaces/babelcloud/babel-agent/hooks.js:45:18)
    at nextResolve (node:internal/modules/esm/hooks:865:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:303:30)
    at handleMessage (node:internal/modules/esm/worker:196:24)
    at checkForMessages (node:internal/modules/esm/worker:138:28)
    at process.<anonymous> (node:internal/modules/esm/worker:157:5) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/duwan/Workspaces/babelcloud/tsed/packages/orm/prisma/lib/esm/.schema/index.js'
}

Node.js v20.11.1
```

To fix it, I need update backup-index.esm.js content
from
```
export * from "./.schema/index.js";
```
 to
```
export * from "../.schema/index.js";
```

File: packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts (hunk 1 above)
Comment (vangie) [reply packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts]: The generate MessageModel.js is already in the form of a function.

```js
...
__decorate([
    Property(() => ConversationModel),
    Required(),
    __metadata("design:type", ConversationModel)
], MessageModel.prototype, "conversation", void 0);
```

File: packages/orm/prisma/src/generator.ts (hunk 2 above)
Comment (Romakita) [reply packages/orm/prisma/src/generator.ts]: Ok let's go ;)

File: packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts (hunk 1 above)
Comment (Romakita) [reply packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts]: hum seems to be strange, because circular ref in ESM should works

Comment (Romakita) [reply packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts]: The problem is adding a condition to not generate decorator on a property will generate also issue because the property won't be mapped in the code.

Comment (Romakita) [reply packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts]: Maybe we need to solve the type set here:

```ts
export function transformFieldToProperty(field: DmmfField, ctx: TransformContext): PropertyDeclarationStructure {
  return {
    kind: StructureKind.Property,
    name: field.name,
    trailingTrivia: "\n",
    type: transformScalarToType(field), // this line set metadata type
    decorators: transformFieldToDecorators(field, ctx)
  };
}
```

Comment (Romakita) [reply packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts]: Found similar issue:
https://stackoverflow.com/questions/60363353/typeorm-onetomany-causes-referenceerror-cannot-access-entity-before-initia

TypeORM has a Relation interface to avoid the circular ref issue + typescript metadata (in this case, the class type won't be set by typescript)

Comment (Romakita) [reply packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts]:
```
export type Relation<T> = T
```

Comment (vangie) [reply packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts]: I'm not very familiar with the details here, so I wonder if you could help implement it. I can help you verify it.

Comment (Romakita) [reply packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts]: sure =)

Comment (Romakita) [reply packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts]: Fixed :) @vangie

Comment (vangie) [reply packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts]: I have tried in my project，everything is OK。@Romakita

Comment (Romakita) [reply packages/orm/prisma/src/generator/transform/transformFieldToDecorators.ts]: perfect go merge :D
